### ISSUE TITLE
Option for local setup with IDE where remote connection is slow

### ISSUE THREAD

**Issue by amitpal-source** [graemerocher/micronaut-oraclecloud-workshop#10]
Hi All,

Please consider the option for local setup with IDE where the remote connection (online IDE) low bandwidth (for certain regions) and the preference of developers (working from home and they would build locally and run in the cloud)

The link from IntelliJ side for pet clinic runs pretty quick as a local test 
![Screenshot 2020-12-07 at 11 18 04](https://user-images.githubusercontent.com/55666802/101307752-25bdd080-3883-11eb-918e-baa3ace5a2a2.png)
![Screenshot 2020-12-07 at 11 52 15](https://user-images.githubusercontent.com/55666802/101307757-29e9ee00-3883-11eb-977c-0854c11012da.png)
![Screenshot 2020-12-07 at 11 52 51](https://user-images.githubusercontent.com/55666802/101307762-2bb3b180-3883-11eb-80a1-03c892aea922.png)

**Comment by graemerocher** [comment]
I added an option so the attendee can run locally and use the H2 in-memory database to complete the workshop
