### ISSUE TITLE
Can't access port 8080

### ISSUE THREAD

**Issue by burtbeckwith** [graemerocher/micronaut-oraclecloud-workshop#17]
I noticed this in the OpenAPI section when trying to see the generated swagger docs, but I can't access the app controller or swagger docs on port 8080. The error is

```
This site can’t provide a secure connection129.146.53.69 sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

and there's no option to ignore the cert issue like before

**Comment by graemerocher** [comment]
you have to use `http` not `https` for port 8080, but the lab should make that more clear
