### ISSUE TITLE
Update Micronaut version

### ISSUE THREAD

**Issue by burtbeckwith** [graemerocher/micronaut-oraclecloud-workshop#18]
The example app uses version 2.1.4

**Comment by graemerocher** [comment]
This is likely the cause of #19

**Comment by pgressa** [comment]
should be in next boot volume .. keeping the issue opened for later verification

**Comment by burtbeckwith** [comment]
The app is correct now (version 2.2.1). Running `mn --version` shows version 2.1.4, although that's not used in the lab

**Comment by graemerocher** [comment]
@pgressa for consistency can we update the locally installed micronaut version as well?

**Comment by pgressa** [comment]
done
