### ISSUE TITLE
Add accurate lab timings

### ISSUE THREAD

**Issue by graemerocher** [graemerocher/micronaut-oraclecloud-workshop#20]
Reminder issue. @burtbeckwith can you add timings for each lab

**Comment by burtbeckwith** [comment]
Did that in https://github.com/graemerocher/micronaut-oraclecloud-workshop/pull/13/commits/483535315ffe0c60d487ea08667a5bd70ca83cc6

**Comment by graemerocher** [comment]
Ah great, thanks!
