### ISSUE TITLE
Annotation on interface not inherited by implementation

### ISSUE THREAD

**Issue by shaunsmith** [graemerocher/micronaut-oraclecloud-workshop#28]
In Lab 7, Mocking Beans show putting @Logged on the getInitialOwners interface method and says “Note that you can apply AOP advice on the interfaces”.  Yet when I remove @Logged from the OwnerService which implements the interface, logging does not happen.

**Comment by graemerocher** [comment]
Hmm weird I remove this from the example app and it still works https://github.com/graemerocher/micronaut-oraclecloud-workshop/commit/48ce5ab2287a9766bacc2063e2353fffa41f8795

Maybe a clean rebuild would have solved it
