### ISSUE TITLE
@MockBean details needed

### ISSUE THREAD

**Issue by shaunsmith** [graemerocher/micronaut-oraclecloud-workshop#29]
Lab 7, Mocking Beans--I think a little more explanation would be good around the wiring that’s taking place.  It seems that when running OwnerControllerTest the @MockBean declaration is overriding the object factory for OwnerOperations in the test application context?  The text just says: "Now if you wish to supply a mock version of OwnerOperations you can use the @MockBean annotation on a method of your test."

**Comment by graemerocher** [comment]
Provided more context, suggestions on further clarifications welcome!
