### ISSUE TITLE
Terraform script fails if tenancy has existing ATP named "mnociatp"

### ISSUE THREAD

**Issue by shaunsmith** [graemerocher/micronaut-oraclecloud-workshop#30]
Ran the scripts in a tenancy where @pgressa is developing and got this failure:

`Error: Service error:InvalidParameter. Provisioning failed because a database named mnociatp already exists in compartment demo. The name must be unique among all Autonomous Data Warehouses and Autonomous Databases in your tenancy in the same region. Specify a different database name and try again.. http status code: 400. Opc request id: be41771aebe115fb387dbbde3ab54ecd/18542F7FF958A790073BD2D837013106/DCC8564137ED3BD8C417DE738D1E310F
`

Can the scripts not generate resource names?

**Comment by graemerocher** [comment]
@pgressa can we generate a unique database name?

**Comment by pgressa** [comment]
@shaunsmith thanks for creating this issue. Initially the lab was not designed to be run in parallel in one tenancy. But as agreed with @graemerocher I'll fix this so that will be supported.
