### ISSUE TITLE
Lab 15 deploy docker container to ocir - Anonymous users are only allowed read access on public repos

### ISSUE THREAD

**Issue by amitpal-source** [graemerocher/micronaut-oraclecloud-workshop#38]
https://graemerocher.github.io/micronaut-oraclecloud-workshop/workshop/?lab=lab-15-going-production#DeployingaContainertoOracleContainerRegistry

[opc@micronaut-hol example]$ ./gradlew dockerPush

> Task :dockerfile
Dockerfile written to: /home/opc/example/build/docker/Dockerfile

> Task :dockerBuild
Building image using context '/home/opc/example'.
Using Dockerfile '/home/opc/example/build/docker/Dockerfile'
Using images 'phx.ocir.io/cloudnative-devrel/micronaut-labs/null/demo:0.1'.
Step 1/7 : FROM openjdk:15-alpine
 ---> f02adfce91a2
Step 2/7 : WORKDIR /home/app
 ---> Running in 0453c2684eae
Removing intermediate container 0453c2684eae
 ---> 5eb75216b329
Step 3/7 : COPY build/layers/libs /home/app/libs
 ---> 7ad42966695f
Step 4/7 : COPY build/layers/resources /home/app/resources
 ---> e9a192f6f3e1
Step 5/7 : COPY build/layers/application.jar /home/app/application.jar
 ---> 7b4abcbbdce6
Step 6/7 : EXPOSE 8080
 ---> Running in b2a61d44365d
Removing intermediate container b2a61d44365d
 ---> 177604274efd
Step 7/7 : ENTRYPOINT ["java", "__ARGS__", "-jar", "/home/app/application.jar"]
 ---> Running in 1584b37af0b8
Removing intermediate container 1584b37af0b8
 ---> 1d983e3c03b0
Successfully built 1d983e3c03b0
Successfully tagged phx.ocir.io/cloudnative-devrel/micronaut-labs/null/demo:0.1
Created image with ID '1d983e3c03b0'.

> Task :dockerPush FAILED
Pushing image 'phx.ocir.io/cloudnative-devrel/micronaut-labs/null/demo:0.1'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerPush'.
> Could not push image: denied: Anonymous users are only allowed read access on public repos

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s
7 actionable tasks: 3 executed, 4 up-to-date
[opc@micronaut-hol example]$

**Comment by pgressa** [comment]
Closing, not part of workshop.
