### ISSUE TITLE
Projector Client Web issue

### ISSUE THREAD

**Issue by amitpal-source** [graemerocher/micronaut-oraclecloud-workshop#8]
Projector Client Web issue

Hi Folks,  

Halfway through the session I get this error
Projector Client Web issue

<img width="1038" alt="Screenshot 2020-12-05 at 12 30 07" src="https://user-images.githubusercontent.com/55666802/101306566-315bc800-3880-11eb-8dae-b3e7fa215df0.png">

**Comment by pgressa** [comment]
cron that checks the projector is listening will be in next boot volume .. keeping the issue opened for later verification
